### ISSUE TITLE
Permit Snake & Raiden to use "disallowed" weapons?

### ISSUE THREAD

**Issue by sagefantasma** [sagefantasma/MGS2-Cheat-Trainer#13]

**Comment by ANTIBigBoss** [comment]
This is the same thing I think will solve the HF Blade issue. I just wanted to put a note in here about what I think the solution may be for this. I imagine the GCX is what tells the game what models/weapons/items to allow as that's how it's worked in other MGS games I've worked on. This is just a shot in the dark but seems plausible.

Side Note: I don't think this would allow Raiden to ever use the USP cause I can't think of any scenario where he'd ever have the USP on his model. Since I imagine part of the game crashing is not having an animation file for the Raiden models on the USP.

**Comment by sagefantasma** [comment]
fun fact, Raiden uses the USP for exactly ONE Special VR mission; you hunt a ghost in the tanker and need the USP light!

anyways, now that people are asking about this, i'm going to start working on it LUL
